application:
  bindAddress: :8449
  production: false
  debug: false
authentication:
  authority: https://tradalia-server:8443/auth/realms/tradalia
messaging:
  address: localhost:8450
  username: rabbit-admin
  password: rabbit.admin
